### ISSUE TITLE
Failed to detect Alien-SVN version

### ISSUE THREAD

**Issue by powerman** [tokuhirom/cpan-outdated#23] opened 2015-04-01 05:36 UTC
```
# cpan-outdated | grep SVN
M/MS/MSCHWERN/Alien-SVN-v1.8.11.0.tar.gz
# cpanm -v M/MS/MSCHWERN/Alien-SVN-v1.8.11.0.tar.gz
...
Successfully installed Alien-SVN-v1.8.11.0
Installing /usr/local/lib64/perl5/5.20.2/x86_64-linux/.meta/Alien-SVN-v1.8.11.0/install.json
1 distribution installed
# perl -MSVN::Core -E 'say $SVN::Core::VERSION'
1.8.11
# cpan-outdated --verbose | grep SVN
SVN::Core                      0       v1.8.11 M/MS/MSCHWERN/Alien-SVN-v1.8.11.0.tar.gz
```

**Comment by joenio** [comment] 2015-07-24 03:26
It seens a limitation of Module::Metadata, I suppose the problem is already related on https://rt.cpan.org/Ticket/Display.html?id=101773

**Comment by joenio** [comment] 2015-07-24 03:29
Maybe a cpan-outdated can ignore modules with version = 0, is there any distribuition/module using 0 (zero) as version number, it is a valid version number?

**Comment by miyagawa** [comment] 2015-07-24 03:38
It is valid, but i think the latest code that was just merged is now ignoring zero, in addition to undef. So i think this ticket can be closed.

**Closed by miyagawa** 2015-07-24 03:38 UTC
